// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdNgcOLrmX7YSCwn8I0SZSD2TDIfOBsXY',
    appId: '1:210748468246:web:3fb27fdd572026256b1937',
    messagingSenderId: '210748468246',
    projectId: 'helponwheels-254d0',
    authDomain: 'helponwheels-254d0.firebaseapp.com',
    storageBucket: 'helponwheels-254d0.appspot.com',
    measurementId: 'G-39MRFEFVJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPmvRnEUvsr8DjeYyOgDdacv-FOA4rkFg',
    appId: '1:210748468246:android:844042ae590a4f836b1937',
    messagingSenderId: '210748468246',
    projectId: 'helponwheels-254d0',
    storageBucket: 'helponwheels-254d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqFMPnKiCc1ejZycL3bK0Ni6E3Fmbnzr8',
    appId: '1:210748468246:ios:4c0533c3d10a335f6b1937',
    messagingSenderId: '210748468246',
    projectId: 'helponwheels-254d0',
    storageBucket: 'helponwheels-254d0.appspot.com',
    iosClientId: '210748468246-m7oa4lhnua61rlhrecg9r1rlki5qfpgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.helponwheels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqFMPnKiCc1ejZycL3bK0Ni6E3Fmbnzr8',
    appId: '1:210748468246:ios:867e0d5d4fa7114b6b1937',
    messagingSenderId: '210748468246',
    projectId: 'helponwheels-254d0',
    storageBucket: 'helponwheels-254d0.appspot.com',
    iosClientId: '210748468246-f2nl6ibid36jrroi67gcvpsskvoilt8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.helponwheels.RunnerTests',
  );
}
